name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm install

      # 4. Run linter (optional)
      - run: npm run lint

      # 5. Run build
      - run: npm run build

      # 6. Log in to Docker Hub (set secrets DOCKER_USERNAME & DOCKER_PASSWORD)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/carshop-server:latest

      # 8. Deploy (example: Docker on remote server via SSH)
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/carshop-server:latest
            docker stop carshop-server || true
            docker rm carshop-server || true
            docker run -d --name carshop-server -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/carshop-server:latest
